
import { Space_Grotesk } from 'next/font/google'
import Header from '../components/Header'
import Footer from '../components/Footer'

import { ThemeProviders } from './theme-providers'

import './globals.css'

import 'css/tailwind.css'
import NextTopLoader from 'nextjs-toploader'
import Provider from '@/components/Provider'

const space_grotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-grotesk',
})

export const metadata = {
  title: 'Agri Review Hub',
  description: 'Generated by Sourabh P',
}

export default function RootLayout({ children }) {
  return (

    <html
      lang='en'
      className={`${space_grotesk.variable} scroll-smooth`}
      suppressHydrationWarning
    >
      <head>
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="theme-color" media="(prefers-color-scheme: light)" content="#fff" />
        <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#000" />
        <link rel="alternate" type="application/rss+xml" href="/feed.xml" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet" />
      </head>

      <body className="bg-white text-black antialiased dark:bg-gray-950 dark:text-white scroll-smooth scrollbar-thin scrollbar-thumb-primary-100 scrollbar-track-gray-200 dark:scrollbar-track-gray-800" suppressHydrationWarning={true}>
        <NextTopLoader
          color="#FFFFFF"
          options={{ showSpinner: false }}
        />
        <Provider>
          <ThemeProviders>
            <section className=''>
              <div className="h-screen font-sans flex flex-col justify-between">
                <div className='h-[60vh] w-full absolute top-0 bg-gradient-to-r from-primary-600 to-primary-500 dark:from-primary-900 dark:to-primary-600 -z-50'></div>
                <Header />
                <main className="mb-auto">{children}</main>
                <Footer />
              </div>
            </section>
          </ThemeProviders>
        </Provider>
      </body>
    </html>
  )
}

